#' @title Parse Route Legs from an API JSON Response
#'
#' @description Extracts the individual legs of each connection from the raw
#' JSON, returning one row per travel segment. The final leg of every
#' connection is the arrival node (it has no onward `exit` stop) and is
#' therefore dropped.
#'
#' @param api_response A list containing the parsed JSON
#' (e.g., loaded from a cached .rds file).
#'
#' @return A tidy tibble with one row per leg, including the boarding and
#' alighting stops, their coordinates, the transport mode and line.
#' @export
#'
#' @importFrom purrr imap_dfr keep pluck
#' @importFrom tibble tibble
parse_route_legs <- function(api_response) {
  # Return an empty tibble if the response is empty or has no connections
  if (
    is.null(api_response$connections) || length(api_response$connections) == 0
  ) {
    return(tibble::tibble())
  }

  # Iterate over each connection (connection_id) and its legs (leg_id)
  purrr::imap_dfr(api_response$connections, function(conn, conn_id) {
    legs_list <- purrr::pluck(conn, "legs", .default = list())

    # Keep only travel legs: the arrival node carries no `exit` stop
    travel_legs <- purrr::keep(legs_list, function(leg) !is.null(leg$exit))

    purrr::imap_dfr(travel_legs, function(leg, leg_id) {
      exit <- leg$exit
      tibble::tibble(
        connection_id = conn_id,
        leg_id = leg_id,
        from_stop = purrr::pluck(leg, "name", .default = NA_character_),
        from_stop_id = purrr::pluck(leg, "stopid", .default = NA_character_),
        to_stop = purrr::pluck(exit, "name", .default = NA_character_),
        to_stop_id = purrr::pluck(exit, "stopid", .default = NA_character_),
        mode = purrr::pluck(leg, "type", .default = NA_character_),
        line = purrr::pluck(leg, "line", .default = NA_character_),
        from_lon = as.numeric(purrr::pluck(leg, "lon", .default = NA_real_)),
        from_lat = as.numeric(purrr::pluck(leg, "lat", .default = NA_real_)),
        to_lon = as.numeric(purrr::pluck(exit, "lon", .default = NA_real_)),
        to_lat = as.numeric(purrr::pluck(exit, "lat", .default = NA_real_))
      )
    })
  })
}

#' @title Parse the Ordered Stop Sequence of Each Route Leg
#'
#' @description Extracts, for every travel leg, the ordered sequence of stops
#' (boarding stop, intermediate stops, alighting stop) with their coordinates.
#' Unlike `parse_route_legs()`, which returns one row per leg, this returns one
#' row per stop, allowing routes to be drawn as polylines through real stops.
#'
#' @param api_response A list containing the parsed JSON
#' (e.g., loaded from a cached .rds file).
#'
#' @return A tidy tibble with one row per stop, ordered by `seq` within each
#' connection/leg, carrying the stop coordinates, transport mode and line.
#' @export
#'
#' @importFrom purrr imap_dfr keep pluck
#' @importFrom tibble tibble
parse_route_points <- function(api_response) {
  # Return an empty tibble if the response is empty or has no connections
  if (
    is.null(api_response$connections) || length(api_response$connections) == 0
  ) {
    return(tibble::tibble())
  }

  # Iterate over each connection (connection_id) and its legs (leg_id)
  purrr::imap_dfr(api_response$connections, function(conn, conn_id) {
    legs_list <- purrr::pluck(conn, "legs", .default = list())

    # Keep only travel legs: the arrival node carries no `exit` stop
    travel_legs <- purrr::keep(legs_list, function(leg) !is.null(leg$exit))

    purrr::imap_dfr(travel_legs, function(leg, leg_id) {
      # Ordered sequence: boarding stop, intermediate stops, alighting stop
      stops <- c(
        list(leg),
        purrr::pluck(leg, "stops", .default = list()),
        list(leg$exit)
      )

      purrr::imap_dfr(stops, function(pt, seq_id) {
        tibble::tibble(
          connection_id = conn_id,
          leg_id = leg_id,
          seq = seq_id,
          stop = purrr::pluck(pt, "name", .default = NA_character_),
          stop_id = purrr::pluck(pt, "stopid", .default = NA_character_),
          lon = as.numeric(purrr::pluck(pt, "lon", .default = NA_real_)),
          lat = as.numeric(purrr::pluck(pt, "lat", .default = NA_real_)),
          mode = purrr::pluck(leg, "type", .default = NA_character_),
          line = purrr::pluck(leg, "line", .default = NA_character_)
        )
      })
    })
  })
}

#' @title Parse and Combine Route Legs from All Cached Queries
#'
#' @description Iterates over the query table, loads the cached API responses
#' generated by `populate_route_cache()`, parses their legs, and combines
#' everything into a single tidy data frame.
#'
#' @param query_table A tibble created by `build_route_query_table()`.
#' @param cache_dir Character. The directory where API responses are saved.
#'
#' @return A tidy tibble with the extracted legs and query metadata.
#' @export
#'
#' @importFrom dplyr mutate select everything
#' @importFrom purrr pmap_dfr
#' @importFrom rlang .data
combine_parsed_legs <- function(query_table, cache_dir = "cache") {
  .data <- rlang::.data

  # Iterate over each row of the query table
  all_legs <- purrr::pmap_dfr(query_table, function(...) {
    row_data <- list(...)

    # Replace colons in time to avoid OS file system errors
    safe_time <- gsub(":", "-", row_data$query_time)

    # Ensure date is a string to avoid formatting issues
    query_date_str <- as.character(row_data$query_date)

    file_name <- paste0(
      "route_",
      row_data$from_station_id, "_",
      row_data$to_station_id, "_",
      query_date_str, "_",
      safe_time, ".rds"
    )

    file_path <- file.path(cache_dir, file_name)

    # Check if the file exists in the cache
    if (!file.exists(file_path)) {
      warning(paste("Cache file not found:", file_path))
      return(tibble::tibble())
    }

    # Load the cached response and parse its legs using the helper function
    legs_data <- parse_route_legs(readRDS(file_path))

    # Add the original query metadata to the parsed result
    if (nrow(legs_data) > 0) {
      legs_data <- legs_data |>
        dplyr::mutate(
          from_city  = row_data$from_city,
          to_city    = row_data$to_city,
          query_date = row_data$query_date,
          query_time = row_data$query_time
        ) |>
        dplyr::select(
          .data$from_city,
          .data$to_city,
          .data$query_date,
          .data$query_time,
          dplyr::everything()
        )
    }
    legs_data
  })

  all_legs
}

#' @title Parse and Combine Route Stops from All Cached Queries
#'
#' @description Iterates over the query table, loads the cached API responses
#' generated by `populate_route_cache()`, parses their stop sequences with
#' `parse_route_points()`, and combines everything into a single tidy data
#' frame ready for drawing simplified route maps.
#'
#' @param query_table A tibble created by `build_route_query_table()`.
#' @param cache_dir Character. The directory where API responses are saved.
#'
#' @return A tidy tibble with the ordered route stops and query metadata.
#' @export
#'
#' @importFrom dplyr mutate select everything
#' @importFrom purrr pmap_dfr
#' @importFrom rlang .data
combine_parsed_points <- function(query_table, cache_dir = "cache") {
  .data <- rlang::.data

  # Iterate over each row of the query table
  all_points <- purrr::pmap_dfr(query_table, function(...) {
    row_data <- list(...)

    # Replace colons in time to avoid OS file system errors
    safe_time <- gsub(":", "-", row_data$query_time)

    # Ensure date is a string to avoid formatting issues
    query_date_str <- as.character(row_data$query_date)

    file_name <- paste0(
      "route_",
      row_data$from_station_id, "_",
      row_data$to_station_id, "_",
      query_date_str, "_",
      safe_time, ".rds"
    )

    file_path <- file.path(cache_dir, file_name)

    # Check if the file exists in the cache
    if (!file.exists(file_path)) {
      warning(paste("Cache file not found:", file_path))
      return(tibble::tibble())
    }

    # Load the cached response and parse its stops using the helper function
    points_data <- parse_route_points(readRDS(file_path))

    # Add the original query metadata to the parsed result
    if (nrow(points_data) > 0) {
      points_data <- points_data |>
        dplyr::mutate(
          from_city  = row_data$from_city,
          to_city    = row_data$to_city,
          query_date = row_data$query_date,
          query_time = row_data$query_time
        ) |>
        dplyr::select(
          .data$from_city,
          .data$to_city,
          .data$query_date,
          .data$query_time,
          dplyr::everything()
        )
    }
    points_data
  })

  all_points
}
