#' @title Parse API JSON Response into a Tidy Table
#'
#' @description Extracts connection details from the raw nested list returned by
#' the search.ch API and formats them into a tidy data frame.
#'
#' @param api_response A list containing the parsed JSON
#' (e.g., loaded from a cached .rds file).
#'
#' @return A tidy tibble containing connection details.
#' @export
#'
#' @importFrom purrr map_dfr pluck
#' @importFrom tibble tibble
parse_route_data <- function(api_response) {

  # Return an empty tibble if the response is empty or has no connections
  if (is.null(api_response$connections) || length(api_response$connections) == 0) {
    return(tibble::tibble())
  }

  # Iterate over each connection and extract key data into a tibble
  parsed_data <- purrr::map_dfr(api_response$connections, function(conn) {

    # Calculate transfers based on the 'legs' array length
    # Subtract 2 because a direct connection has 2 legs (1 travel leg + 1 arrival node)
    legs_list <- purrr::pluck(conn, "legs", .default = list())
    num_transfers <- max(0L, as.integer(length(legs_list)) - 2L)

    tibble::tibble(
      departure = purrr::pluck(conn, "departure", .default = NA_character_),
      arrival   = purrr::pluck(conn, "arrival",   .default = NA_character_),
      duration  = as.numeric(purrr::pluck(conn, "duration", .default = NA_real_)),
      transfers = num_transfers
    )
  })

  return(parsed_data)
}



#' @title Parse and Combine All Cached Route Queries
#'
#' @description Iterates over the query table, loads the cached API responses
#' generated by `populate_route_cache()`, parses them, and combines everything
#' into a single tidy data frame.
#'
#' @param query_table A tibble created by `build_route_query_table()`.
#' @param cache_dir Character. The directory where API responses are saved.
#'
#' @return A tidy tibble with the extracted connections and query metadata.
#' @export
#'
#' @importFrom dplyr mutate select everything
#' @importFrom purrr pmap_dfr
#' @importFrom rlang .data
combine_parsed_queries <- function(query_table, cache_dir = "cache") {
  .data <- rlang::.data

  # Use purrr::pmap_dfr to iterate over each row of the query table
  all_routes <- purrr::pmap_dfr(query_table, function(...) {
    row_data <- list(...)

    # MATCH THE NEW CACHE FILENAME LOGIC:
    # "route_{from}_{to}_{date}_{HH-MM}.rds"
    safe_time <- gsub(":", "-", row_data$query_time)

    # Ensure date is a string to avoid formatting issues
    query_date_str <- as.character(row_data$query_date)

    file_name <- paste0(
      "route_",
      row_data$from_station_id, "_",
      row_data$to_station_id, "_",
      query_date_str, "_",
      safe_time, ".rds"
    )

    file_path <- file.path(cache_dir, file_name)

    # Check if the file exists in the cache
    if (!file.exists(file_path)) {
      warning(paste("Cache file not found:", file_path))
      return(tibble::tibble())
    }

    # Load the cached response and parse it using the helper function
    api_response <- readRDS(file_path)
    parsed_data <- parse_route_data(api_response)

    # Add the original query metadata to the parsed result
    if (nrow(parsed_data) > 0) {
      parsed_data <- parsed_data |>
        dplyr::mutate(
          from_city       = row_data$from_city,
          to_city         = row_data$to_city,
          from_station_id = row_data$from_station_id,
          to_station_id   = row_data$to_station_id,
          query_date      = row_data$query_date,
          query_time      = row_data$query_time
        ) |>
        # Reorder columns explicitly
        dplyr::select(
          .data$from_city,
          .data$to_city,
          .data$from_station_id,
          .data$to_station_id,
          .data$query_date,
          .data$query_time,
          .data$duration,
          dplyr::everything()
        )
    }
    return(parsed_data)
  })

  return(all_routes)
}
